### ISSUE TITLE
Hey men, thanks u for reply. And not show urs ENV!

### ISSUE THREAD

**Issue by colo13verdadeo** [toutpuissantged/cryptoMonsterHot#5]
First: Thanks u for reply my issues in coingrecko.

The objective of this message is to let you know that your env is seen! 
You must hide it from the public!.

**Comment by toutpuissantged** [comment]
> First: Thanks u for reply my issues in coingrecko.
> 
> The objective of this message is to let you know that your env is seen! You must hide it from the public!.

yes thank you, but since it was a test program I didn't want to make my life more complex, because on the production cloud server I just made a git clone and npm run start, thank you very much for the remark
